name: pltnum
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.9.5=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=14.0.2=h374c478_1
  - attrs=23.1.0=py311h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - biopython=1.84=py311h331c9d8_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py311h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - cryptography=42.0.5=py311hdda0065_1
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - datasets=2.19.1=py311h06a4308_0
  - dill=0.3.8=py311h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - fsspec=2024.3.1=py311h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - huggingface_hub=0.23.1=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.1.7=0
  - libcurand=10.3.6.82=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.43.0=py311h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.4=py311h5eee18b_0
  - multiprocess=0.70.15=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - numba=0.60.0=py311h4bc866e_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_1
  - openssl=3.3.1=h4bc722e_2
  - orc=1.7.4=hb3bc3d3_1
  - packaging=24.1=py311h06a4308_0
  - pandas=2.1.1=py311ha02d727_0
  - pillow=10.3.0=py311h5eee18b_0
  - pip=24.0=py311h06a4308_0
  - pyarrow=14.0.2=py311hb6e97c4_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=24.0.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - python_abi=3.11=2_cp311
  - pytorch=2.3.1=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py311h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.2=py311h24d97f6_1
  - scikit-learn=1.2.2=py311h6a678d5_1
  - scipy=1.13.1=py311h08b1b3b_0
  - setuptools=69.5.1=py311h06a4308_0
  - shap=0.45.1=cpu_py311h9c1f9ec_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.15.1=py311h22610ee_0
  - torchaudio=2.3.1=py311_cu121
  - torchtriton=2.3.1=py311
  - torchvision=0.18.1=py311_cu121
  - tqdm=4.66.4=py311h92b7b1e_0
  - transformers=4.38.2=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=1.26.19=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.43.0=py311h06a4308_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py311h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2